= libmmel

ifdef::env-github[]

image:https://img.shields.io/github/v/release/paneron/libmmel?display_name=tag&include_prereleases&sort=semver[
  GitHub release (latest SemVer including pre-releases),
  link="https://www.npmjs.com/package/@paneron/libmmel"]

image:https://github.com/paneron/libmmel/actions/workflows/macos-latest.yml/badge.svg[
  alt="Build/release (macOS)",
  link="https://github.com/paneron/libmmel/actions/workflows/macos-latest.yml"]
image:https://github.com/paneron/libmmel/actions/workflows/ubuntu-latest.yml/badge.svg[
  alt="Build/release (Ubuntu)",
  link="https://github.com/paneron/libmmel/actions/workflows/ubuntu-latest.yml"]
image:https://github.com/paneron/libmmel/actions/workflows/windows-latest.yml/badge.svg[
  alt="Build/release (Windows)",
  link="https://github.com/paneron/libmmel/actions/workflows/windows-latest.yml"]

image:https://github.com/paneron/libmmel/actions/workflows/lint.yml/badge.svg[
  alt="Lint",
  link="https://github.com/paneron/libmmel/actions/workflows/lint.yml"]
image:https://github.com/paneron/libmmel/actions/workflows/audit.yml/badge.svg[
  "Audit Status",
  link="https://github.com/paneron/libmmel/actions/workflows/audit.yml"]

endif::[]

== Introduction

This folder contains the data model for MMEL model. Note that this model does not contain runtime information. So, there is another model 'EditorModel' which is like an upgraded version of the model for the runtime.

== Folders

- The interface folder
  * Contains the data structures of different elements in the model
- The handler folder
  * Contains the codes for parsing MMEL structure to MMEL model
- The util folder
  * Provides other utility functions (Check the comments inside)

== MMEL.ts

It is the main model definition and API.
