= libmmel

ifdef::env-github[]

image:https://img.shields.io/github/v/release/paneron/libmmel?display_name=tag&include_prereleases&sort=semver[
  GitHub release (latest SemVer including pre-releases),
  link="https://www.npmjs.com/package/@paneron/libmmel"]
image:https://github.com/paneron/libmmel/actions/workflows/build-and-test.yml/badge.svg[
  alt="Build / Test",
  link="https://github.com/paneron/libmmel/actions/workflows/build-and-test.yml"]
image:https://github.com/paneron/libmmel/actions/workflows/lint.yml/badge.svg[
  alt="Lint",
  link="https://github.com/paneron/libmmel/actions/workflows/lint.yml"]
image:https://github.com/paneron/libmmel/actions/workflows/audit.yml/badge.svg[
  "Audit Status",
  link="https://github.com/paneron/libmmel/actions/workflows/audit.yml"]

endif::[]

== Introduction

This library implements serialization and deserialization of MMEL models,
and provides exported interfaces for relevant data types.

NOTE:  This model does not contain runtime information.
Any such runtime information should be implemented in a separate model.

== Installation

Run:

```console
npm install @paneron/libmmel
```

== Usage Examples

```typescript
import { textToMMEL, MMELToText } from '@paneron/libmmel';
import type { MMELModel } from '@paneron/libmmel';


const text = '... insert MMEL text here ...';
const mmel: MMELModel = textToMMEL(text);
console.log(MMELToText(mmel));

```

== Folder Structure

- `interface/`
  * Contains the data structures of different elements in the model
- `handler/`
  * Contains the codes for parsing MMEL structure to MMEL model
- `util/`
  * Provides other utility functions (Check the comments inside)

== Roadmap

- link:https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c?permalink_comment_id=3850849#gistcomment-3850849[Use pure ESM^].
