name: build-and-test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - main
      - 'release/v*'
    tags-ignore:
      - v*
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - '/vcpkg.txt'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'
      - '.github/workflows/*.yml'
      - '!.github/workflows/build-and-test.yml'
      - '!.github/workflows/build.yml'
      - '!.github/workflows/test.yml'
  pull_request:
    paths-ignore:
      - '/*.sh'
      - '/.*'
      - '/_*'
      - '/vcpkg.txt'
      - 'docs/**'
      - '**.adoc'
      - '**.md'
      - '**.nix'
      - 'flake.lock'

jobs:
  build:
    strategy:
      matrix:
        node: [16, 18, 20]

    uses: ./.github/workflows/build.yml
    with:
      os: ubuntu-latest
      node: ${{ matrix.node }}

  test:
    strategy:
      matrix:
        node: [16, 18, 20]

    uses: ./.github/workflows/test.yml
    with:
      os: ubuntu-latest
      node: ${{ matrix.node }}
