name: build

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      node:
        required: false
        type: string
        default: ${{ vars.DEFAULT_NODE_VERSION }}
      CACHE_DIR:
        required: false
        type: string
        default: dist

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.os }}

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Calculate cache keys
        # Because the exact same hashFiles invocation produces different
        # results down the file
        id: build-cache-keys
        shell: bash
        run: |
          if command -v shasum; then sum() { shasum -a 256 "$@"; } ; else sum() { sha256sum "$@"; }; fi
          fragment="${{ runner.os }}-${{ inputs.node }}-${{ hashFiles('package.json', '*.ts', '**/src/**', '**/.swcrc', '**/.npmrc', '**/tsconfig*.json', '**/pnpm-lock.yaml') }}"
          build_fragment="${{ hashFiles('.github/workflows/build.yml') }}"
          echo "build-key=build-${fragment}-${build_fragment}" | tee -a $GITHUB_OUTPUT

      - name: Restore build cache
        id: build_cache
        uses: actions/cache@v3
        with:
          path: ${{ inputs.CACHE_DIR }}
          key: ${{ steps.build-cache-keys.outputs.build-key }}

      - uses: actions/setup-node@v3
        if: steps.build_cache.outputs.cache-hit != 'true'
        id: setup-node
        with:
          node-version: ${{ inputs.node }}

      - uses: pnpm/action-setup@v2
        if: steps.build_cache.outputs.cache-hit != 'true'
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8
          run_install: false

      # See: https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time
      - name: Get pnpm store directory
        if: steps.build_cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v3
        if: steps.build_cache.outputs.cache-hit != 'true'
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/.npmrc', '**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        if: steps.build_cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile --strict-peer-dependencies

      - name: Build cache on ${{ runner.os }}
        if: steps.build_cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          pnpm run dist

      - name: Test build artifacts sanity
        if: steps.build_cache.outputs.cache-hit != 'true'
        shell: bash
        run: |
          pnpm run test-dist
